blank_issues_enabled: false
contact_links:
    - name: ⚠️ Source issue
      url: https://github.com/san9-dunes/neyon-parsers-redo/issues
      about: If you have a problem with a specific **manga source** or want to propose a new one, please open an issue in the neyon-parsers-redo repository instead
